# Generated by Django 5.2.4 on 2025-09-06 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_course_material_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('book', 'Book'), ('notes', 'Notes'), ('other', 'Other')], max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='resources/')),
                ('contact_info', models.CharField(help_text='Email or phone', max_length=200)),
                ('exchange_type', models.CharField(choices=[('trade', 'Trade'), ('donation', 'Donation')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
