# Generated by Django 5.2.4 on 2025-09-26 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_course_material_alter_course_tutor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_role',
            field=models.CharField(choices=[('student', 'Student'), ('tutor', 'Tutor')], default='student', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='material',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='tutor',
            field=models.ForeignKey(limit_choices_to={'is_tutor': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resource',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='department',
            field=models.CharField(choices=[('MCA', 'Master of Computer Applications'), ('BCA', 'Bachelor of Computer Applications'), ('BTech-IT', 'Bachelor of Technology in Information Technology'), ('BeTech-AI', 'Bachelor of Technology in Artificial Intelligence'), ('BeTech-CS', 'Bachelor of Technology in Computer Science'), ('BBA', 'Bachelor of Business Administration'), ('MBA', 'Master of Business Administration')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
